MicroserviceECommerce/MicroserviceECommerce.MVCUI/Controllers/ShopCartController.cs
using MicroserviceECommerce.MVCUI.Filters;
using MicroserviceECommerce.MVCUI.HTTPHelperMethpds;
using MicroserviceECommerce.MVCUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MicroserviceECommerce.MVCUI.Controllers
{
    public class ShopCartController : Controller
    {
        // GET: ShopCart
        [LoginFilter]
        public ActionResult CartView()
        {
            return View();
        }
        [LoginFilter]
        [HttpGet]
        public ActionResult AddShopCart(int id)
        {
            ProductsModel product = new ProductsModel();
            if (Session["Cart"] == null)
            {
                var cust = (CustomersModel)Session["Login"];
                List<ItemonCartModel> cart = new List<ItemonCartModel>();
                cart.Add(new ItemonCartModel { Product = HTTPHelpers.GetMethod<ProductsModel>("http://localhost:37796/", "Products/GetProductDetail", RestSharp.Method.GET, id), Quantity = 1, CustomerID = cust.CustomerID });
                Session["Cart"] = cart;
            }
            else
            {
                List<ItemonCartModel> cart = (List<ItemonCartModel>)Session["Cart"];
                int index = cart.FindIndex(a => a.Product.ProductID == id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new ItemonCartModel { Product = HTTPHelpers.GetMethod<ProductsModel>("http://localhost:37796/", "Products/GetProductDetail", RestSharp.Method.GET, id), Quantity = 1 });
                }
                Session["Cart"] = cart;
            }
            return RedirectToRoute(new { controller = "Products", action = "GetProducts" });
        }
        [LoginFilter]
        public ActionResult DeleteShopCart(int id)
        {
            List<ItemonCartModel> cart = (List<ItemonCartModel>)Session["Cart"];
            int index = cart.FindIndex(a => a.Product.ProductID == id);
            cart.RemoveAt(index);
            Session["Cart"] = cart;
            return RedirectToAction("CartView");
        }

        public ActionResult UpdateShopCart(FormCollection form)
        {
            List<ItemonCartModel> cart = (List<ItemonCartModel>)Session["Cart"];
            int index = cart.FindIndex(a => a.Product.ProductID == Convert.ToInt32(form["id"]));
            cart[index].Quantity= Convert.ToInt32(form["quantity"]);
            Session["Cart"] = cart;
            return RedirectToAction("CartView");
        }
    }
}

MicroserviceECommerce/MicroserviceECommerce.MVCUI/Views/ShopCart/CartView.cshtml
@using MicroserviceECommerce.MVCUI.Models;
@{
    ViewBag.Title = "CartView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table">
    <tr>
        <th>ProductID</th>
        <th>Product Name</th>
        <th>Category</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Sub Total</th>
        <th>Remove</th>
    </tr>
    @if (Session["Cart"] != null)
    {
        foreach (var item in (List<ItemonCartModel>)Session["Cart"])
        {
            <tr>
                <td>@item.Product.ProductID</td>
                <td>@item.Product.ProductName</td>
                <td>@item.Product.CategoryID</td>
                <td>@item.Product.UnitPrice</td>
                <td>
                    @using (Html.BeginForm("UpdateShopCart", "ShopCart"))
                    {
                        <div class="input-group">
                            @Html.TextBox("quantity", $"{ item.Quantity}", new { @class = "form-control", type = "number", min = 1, max = item.Product.UnitsInStock, style = "width:70px" })
                            @Html.Hidden("id",  $"{ item.Product.ProductID}")
                            <input type="submit" value="Update" class="btn btn-success" />
                        </div>
                    }
                </td>
                <td>@(item.Product.UnitPrice * item.Quantity)</td>
                <td>
                    <a class="btn btn-warning btn-sm" href="@Url.Action("DeleteShopCart", "ShopCart", new { id = item.Product.ProductID })">Remove</a>
                </td>
            </tr>
        }
        <tr>
            <td align="right" colspan="6">Sum</td>
            <td>
                @{
                    List<ItemonCartModel> cart = (List<ItemonCartModel>)Session["cart"];
                    var Total = cart.Sum(x => x.Product.UnitPrice * x.Quantity);
                }
                @Total
            </td>
            <td align="right" colspan="6"><a class="btn btn-success btn-sm" href="~/Orders/PutOrders/">Buy</a></td>
        </tr>
    }
</table>